spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_plantes?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true  # Permet les références circulaires dans Spring (ce n'est pas recommandé mais peut être utile dans certains cas)

logging:
  file:
    path: ./logging/global/logs
    name: ${logging.file.path}/global.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [  %-5level  -------  %logger{1.}  ]        - %msg%n"  # Console log format
  logback:
    rollingpolicy:
      max-file-size: 5MB
    max-history: 5
